version: '3'
services:
    gateway:
        build: gateway
        ports:
            - "5000:8080"
        links:
            - log:logservice
            - rabbit:rabbit

    log:
        build: log

    rabbit:
        hostname: rabbit
        environment:
            - RABBITMQ_ERLANG_COOKIE='secret_cookie'
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
            - "5672:5672"
        tty: true
        volumes:
            # - rabbit:/var/lib/rabbitmq
            - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        command:  bash -c "sleep 10; rabbitmq-server;"

#Persistent data, stored in docker/volumes locally
volumes:
    rabbit:
        driver: local
