version: '3'
services:
    gateway:
        build: gateway
        ports:
            - "5000:8080"
        links:
            - rabbit:rabbit

    rabbit:
        hostname: rabbit
        environment:
            - RABBITMQ_ERLANG_COOKIE='secret_cookie'
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
            - "5672:5672"
        tty: true
        volumes:
            - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        command:  bash -c "sleep 10; rabbitmq-server;"

    log:
        build: log
        links:
            - rabbit:rabbit
        depends_on:
            - rabbit
        command: >
          sh -c "
            while ! nc -z rabbit 5672;
            do
              echo sleeping;
              sleep 1;
            done;
            echo Connected;
            ls;
            python3 main.py;
          "

#Persistent data, stored in docker/volumes locally
volumes:
    rabbit:
        driver: local
